### PR TITLE
Add preserveFullCustomRegistry to not swallow part of image

### PR DESCRIPTION
**Pull request by nashant**
This is to stop GetImageURN from swallowing part of the image tag when
setting a customImageRegistry with a / in it. Original behaviour is,
when a registry of `example.io/public` is used with an image of
`portworx/oci-monitor`, for the image to become
`emaple.io/public/oci-monitor`. Setting this to true will preserve the
full path and the image will be `example.io/public/portworx/oci-monitor`

Remediates Pure portal ticket #01194532

### CODE REVIEW

**Review by piyush-nimbalkar — APPROVED** [review]

**Comment by piyush-nimbalkar** [comment]
Thank you for making the changes, @nashant!

**Comment by nashant** [comment]
No problem whatsoever, that's the advantage of open source! When do you think you would be able to cut a release so we can crack on with our daemonset->operator migration?

**Comment by piyush-nimbalkar** [comment]
We are planning to release 1.8.0 (with this change) around end of the next month. We will keep you posted through the internal channels.
Thanks again!

**Comment by nashant** [comment]
Could you please cut a 1.7.1 release with just this commit? End of next month is no good to us, we're already well behind with migrating from daemonset to operator.

**Pull request merged**
