### PR TITLE
PWX-33069: Upgrading golang to 1.20.7

### PR DESCRIPTION
**Pull request by zoxpx**
* also updating linter-tools

**What this PR does / why we need it**:

We're changing golang-compiler version ~1.19.1~ -> `1.20.7`

Note, there was a _drastic_ reduction of `vendor/` -files
* this is due to removal of `github.com/golangci/golangci-lint@v1.50.1` code-dependency
* the golangci-lint@v1.50.1 is buggy (hangs + memory-leak w/ go-1.20), and also
* we switched to using a `golangci-lint` binary - so we don't need to "keep the sources of the tool"

**Which issue(s) this PR fixes** (optional)
Closes # PWX-33069

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by zoxpx** [comment]
Ping -- any chance of getting a review on this PR ?

Note, the PR "looks scary" (1800 vendor/ -files removed) -- but this is because we had `golangci-lint` sources checked in (used w/ `make lint`).  Since there is no need to keep the linter-tool sources checked in, I removed them, and caused 1800-files diff.

**Review by nikita-bhatia — APPROVED** [review]
LGTM, please run operater regression job to make sure nothing is breaking before merging the PR :)

**Comment by zoxpx** [comment]
Looks like most Operator tests are taking edge-install.portworx.com as an "input parameter", so
* I've tested this PR manually, and
* will retest once the code is committed in `master`-branch, and before cherry-picking to `px-rel-23.7.0`

**Comment by zoxpx** [comment]
Security scan report @ https://aetos.pwx.purestorage.com/security/Operator/master/2023-08-24-00-45-59-261286
* 0 criticals, 12 highs 

Jenkins test @ https://jenkins.pwx.dev.purestorage.com/job/Operator/view/Operator%20Release%20Dashboard/job/op-basic-hotfix/32/
* PASSED

**Comment by zoxpx** [comment]
Proceeding to cherry-pick to `px-rel-23.7.0`

**Pull request merged**
