### PR TITLE
PWX-30520: Upgrading JWT package

### PR DESCRIPTION
**Pull request by zoxpx**
* replacing github.com/dgrijalva/jwt-go with github.com/golang-jwt/jwt/v4
* upgrading github.com/libopenstorage/openstorage

Additional:
* fixing `copylocks: assignment copies lock value to desiredRole: github.com/libopenstorage/openstorage/api.SdkRole contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)`
* fixing `SA1019: jwt.StandardClaims is deprecated: Use RegisteredClaims instead for a forward-compatible way to access registered claims in a struct. (staticcheck)`

**What this PR does / why we need it**:

We're upgrading JWT package due to security issues

* replacing ~github.com/dgrijalva/jwt-go~ with newer `github.com/golang-jwt/jwt/v4`
* upgrading `github.com/libopenstorage/openstorage` from (1.5 years old) 43eadb190637 to recent 7f88436db3de
  - note, this update has also upgraded/replaced the same JWT package, in openstorage project

Additional:
* fixing `copylocks: assignment copies lock value to desiredRole: github.com/libopenstorage/openstorage/api.SdkRole contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)`
  - done by switching to pointer-refereces in drivers/storage/portworx/component/auth.go and drivers/storage/portworx/components_test.go
* fixing `SA1019: jwt.StandardClaims is deprecated: Use RegisteredClaims instead for a forward-compatible way to access registered claims in a struct. (staticcheck)`
  - done by ignoring this deprecation warning in drivers/storage/portworx/component/auth.go
* note, running `go mod tidy` has brought in additional package upgrades (primarily `github.com/prometheus/{client_golang,procfs}/` packages)

**Which issue(s) this PR fixes** (optional)
Closes # PWX-30520

**Special notes for your reviewer**:

### CODE REVIEW

**Review by piyush-nimbalkar — APPROVED** [review]

**Comment by zoxpx** [comment]
@piyush-nimbalkar -- heads-up, significant modification required after your review (see [04e7d5f](https://github.com/libopenstorage/operator/pull/1065/commits/04e7d5f5694200fff10667fb099ce831f23242cd))

**Comment by zoxpx** [comment]
**CAUTION**:
The [4503ed8](https://github.com/libopenstorage/operator/pull/1065/commits/4503ed8b8100be398a7d5e78663d188010613efa) overrides, and greatly simplifies this PR.
* we are now relying on the new `master`-branch, which already has updated `openstorage` pacakge

**Comment by zoxpx** [comment]
Thanks for the review Piyush -- merging into `master`-branch
* cherry-pick to `px-rel-23.6.0` pending on https://github.com/libopenstorage/operator/pull/1080

**Comment by zoxpx** [comment]
Cherry-picking into `px-rel-23.6.0` branch

**Pull request merged**
