### PR TITLE
PTX-23278 Change PVC controller validation logic for 24.1.0+

### PR DESCRIPTION
**Pull request by nikolaypopov**
Change PVC controller validation logic for 24.1.0+, we are now not deploying PVC controller on OCP for 24.1+

### CODE REVIEW

**Review by nilanto07-px — APPROVED** [review]
LGTM

**Comment by zoxpx** [comment]
Wait, wait.. I'm a bit confused by this PR
* with this PR, you seem to DISABLE the automatic deployment of PVC-controller, if the `PX-Operator >= 24.1.0`

How can this possibly work?
* the operator does not carry a code that can be used to replace PVC-controller -- this does not seem right..

@piyush-nimbalkar, would you mind also taking a quick look?

**Comment by zoxpx** [comment]
> Wait, wait.. I'm a bit confused by this PR
> 
> * with this PR, you seem to DISABLE the automatic deployment of PVC-controller, if the `PX-Operator >= 24.1.0`
> 
> How can this possibly work?
> 
> * the operator does not carry a code that can be used to replace PVC-controller -- this does not seem right..
> 
> @piyush-nimbalkar, would you mind also taking a quick look?

Actually -- @nikolaypopov pointed out this method is used ONLY for unit-tests  (not the production code)
* the production-code func is at https://github.com/libopenstorage/operator/blob/master/drivers/storage/portworx/component/pvccontroller.go#L93 --
* ... it looks similar, but it does not carry the same modification

**Review by zoxpx — APPROVED** [review]
My concerns were addressed -- thanks Nikolay

**Pull request merged**
