### PR TITLE
PWX-31025_px-23.10.0: Migration status fixes

### PR DESCRIPTION
**Pull request by zoxpx**
**What this PR does / why we need it**:

This fix is based on partial merges of the PWX-27765 fixes done on `master`-branch, and never back-ported, specifically:
* https://github.com/libopenstorage/operator/pull/870
* https://github.com/libopenstorage/operator/pull/873

**ISSUE**:
* the `DaemonSet -> StorageCluster` migration relies on the regular Operator behavior triggered by `storagecluster.go::Reconcile()`
* however, the `Reconcile()` will updates `StorageCluster.Status` object as it's updating PX cluster,
* more specifically, the `STC.Status` update that "migration is complete" will get overwritten (and lost) by the concurrent "portworx component" status update
* as a consequence -- `kubectl get stc` is perpetually stuck on `Initializing` state, and never switches to `Running` -- even after the migration completed successfully

**FIX**:
* as a fix, we moved the "migration is complete" status-update, and bundled it together with "portworx component" status update

Additional fixes:
* adding more verbose error-logs, also
* introduced new `UpdateLiveStorageClusterStatusCB()` and `UpdateLiveStorageClusterCB()` utility functions, that simplify `get-update-put` update steps on "live" StorageCluster and StorageCluster.Status objects

**Which issue(s) this PR fixes** (optional)
Closes # PWX-31025

**Special notes for your reviewer**:

Quick test:

Tracking the STC-status during the migration:
```
# kubectl get stc -w  | ts '%M:%S'
...
33:09 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   12m
33:16 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   12m
33:23 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   12m
33:30 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   12m
33:37 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   13m
33:44 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   13m
33:50 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Initializing   2.13.10   13m
33:50 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Running        2.13.10   13m
34:04 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Running        2.13.10   13m
34:18 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Running        2.13.10   13m
34:31 px-cluster-foo-790da85eec85   3a1e1809-bcc0-437b-899a-fe62367f8ac7   Running        2.13.10   13m
```
* note, the STC status is now correctly transitioning from `Initializing` to `Running` when Migration completes..

### CODE REVIEW

**Review by piyush-nimbalkar — APPROVED** [review]
I was working on the cherrypick of [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765) as it was assigned to me. 
Thanks for fixing this. I will close [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765).

**Comment by zoxpx** [comment]
> I was working on the cherrypick of [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765) as it was assigned to me. Thanks for fixing this. I will close [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765).

You might still want to eyeball the https://github.com/libopenstorage/operator/pull/853 PR
* that was part of the same [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765) ticket, and I included very little (nothing?) in this PR

**Comment by piyush-nimbalkar** [comment]
> > I was working on the cherrypick of [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765) as it was assigned to me. Thanks for fixing this. I will close [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765).
> 
> You might still want to eyeball the #853 PR
> 
> * that was part of the same [PWX-27765](https://portworx.atlassian.net/browse/PWX-27765) ticket, and I included very little (nothing?) in this PR

I already did that yesterday. There were 4 commits out of which 3 are already part of 23.10.0. The only missing changes was the migration status fix, which is now part of this PR.

**Comment by zoxpx** [comment]
Thanks for the review -- merging this PR

**Pull request merged**
