### PR TITLE
PWX-22998 bump px-node-wiper to 2.10.0

### PR DESCRIPTION
**Pull request by harsh-px**
Signed-off-by: Harsh Desai <hadesai@purestorage.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by zoxpx — APPROVED** [review]
I'm a bit confused -- looks like the `portworx/px-node-wiper:2.10.0` and `portworx/px-node-wiper:2.5.0` are the exact the same image?

```
REPOSITORY              TAG      IMAGE ID       CREATED             SIZE                                                                                                                                                      
portworx/px-node-wiper  2.10.0   b87c83f901ba   About an hour ago   645MB
portworx/px-node-wiper  2.5.0    b87c83f901ba   About an hour ago   645MB
```

**Comment by harsh-px** [comment]
Yeah, the talisman project CI settings was always pushing every build as 2.5.0. I've now fixed it to push as latest.

https://app.travis-ci.com/github/portworx/talisman/settings

**Comment by piyush-nimbalkar** [comment]
@harsh-px now that the image is the same, I am assuming this can be used for older px versions as well, right?
Also, we will need to update the spec generator as well.
cc: @haibinxie

**Comment by harsh-px** [comment]
> @harsh-px now that the image is the same, I am assuming this can be used for older px versions as well, right?
Also, we will need to update the spec generator as well.

Yes, this will work on the old versions too. I'm updating the spec generator as well.

**Pull request merged**
