### PR TITLE
OPERATOR-322 fix DTR vulnerability scan issues

### PR DESCRIPTION
**Pull request by haibinxie**
**What this PR does / why we need it**:
Fix DTR scan issues:
https://portworx.atlassian.net/browse/OPERATOR-322

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:
Screen Shot 2021-05-11 at 11 49 24 AM

### CODE REVIEW

**Comment by piyush-nimbalkar** [comment]
Is the uploaded screenshot comparing the old scan and new scan? So, there is only one critical issue?

**Comment by haibinxie** [comment]
> Is the uploaded screenshot comparing the old scan and new scan? So, there is only one critical issue?

@piyush-nimbalkar Yes.

**Review by piyush-nimbalkar — APPROVED** [review]
Can you upload this to the redhat partner portal and check if the operator image scan passes fine? Don't publish it, but just upload and let the scan run.
Merge this PR is the scan passes fine with no flags.

**Comment by haibinxie** [comment]
> Can you upload this to the redhat partner portal and check if the operator image scan passes fine? Don't publish it, but just upload and let the scan run.
> Merge this PR is the scan passes fine with no flags.

@piyush-nimbalkar The scan on redhat portal passed.
Screen Shot 2021-05-12 at 2 51 33 PM

**Pull request merged**
