### PR TITLE
Reconcile components in order of their priority

### PR DESCRIPTION
**Pull request by piyush-nimbalkar**
We should install certain components like PSP, security
before other components start to resolve run time
dependencies.

Signed-off-by: Piyush Nimbalkar <pnimbalkar@purestorage.com>

### CODE REVIEW

**Comment by harsh-px** [comment]
what was the actual issue here? Looking at the change, we are creating PSPs and security components first. Did the reverse order cause the autopilot deployment to get stuck in blocked state?

**Comment by piyush-nimbalkar** [comment]
Yes, autopilot was getting blocked. As Kubernetes doesn't retry starting the pod, it remains in blocked state. 
Restarting the pod works, but it is inconvenient.

**Comment by harsh-px** [comment]
Makes sense.

> As Kubernetes doesn't retry starting the pod, it remains in blocked state.

So much for being eventually consistent :)

**Review by adityadani — APPROVED** [review]
lgtm

**Pull request merged**
