### PR TITLE
[OPERATOR-693] Disable bundle validation for now due to v1alpha1 CRD …

### PR DESCRIPTION
**Pull request by pure-jliao**
…issue

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by haibinxie** [comment]
we shall investigate the fix to the bundle first

**Comment by pure-jliao** [comment]
> 



> we shall investigate the fix to the bundle first

we may need an ocp cluster for that. and it's blocking cherrypick all changes. can we have all the payload in and start testing? we could investigate this issue during or after fc, what do you think? @haibinxie

**Comment by haibinxie** [comment]
> > 
> 
> > we shall investigate the fix to the bundle first
> 
> we may need an ocp cluster for that. and it's blocking cherrypick all changes. can we have all the payload in and start testing? we could investigate this issue during or after fc if have time, what do you think? @haibinxie

sounds good, we can start prior to FC so it does not block system tests.

**Review by haibinxie — APPROVED** [review]

**Comment by haibinxie** [comment]
BTW, could you create a ticket so we can track the dev/test estimate

**Comment by pure-jliao** [comment]
> BTW, could you create a ticket so we can track the dev/test estimate
already have a ticket, will add the label

**Pull request merged**
