### PR TITLE
PWX-31199: 23.5.0 cherry-pick for autopilot RBAC/security fixes

### PR DESCRIPTION
**Pull request by ezhang-px**
**What this PR does / why we need it**:
Cherry-picked two previous commits in master about deprecating the use of podsecuritypolicies and limiting number of RBAC permissions for 23.5.0 release

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by zoxpx — APPROVED** [review]
Thank you Eugene

**Comment by zoxpx** [comment]
BTW.. did you already fix `master`, or you intend to cherry-pick this PR into master-branch?

**Comment by ezhang-px** [comment]
> BTW.. did you already fix `master`, or you intend to cherry-pick this PR into master-branch?

Hey Zoran, thanks for helping review it. These two changes have been merged into master already and right now I'm just cherry-picking them from there for 23.5.0 release.

**Comment by ezhang-px** [comment]
Have to close this one (not merged) due to the branch protection issue with release branch prefix mentioned at https://purestorage.slack.com/archives/C03TQP3L724/p1684357590478379?thread_ts=1684354098.343209&cid=C03TQP3L724
which prevents me from pushing more commit
Will submit another one and linked to this

**Pull request closed without merging**
